/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huenei.exolgan.services.service.base;

import com.huenei.exolgan.services.model.ProcessOrderDetail;
import com.huenei.exolgan.services.service.ProcessOrderDetailLocalService;
import com.huenei.exolgan.services.service.ProcessOrderLocalService;
import com.huenei.exolgan.services.service.ReservationLocalService;
import com.huenei.exolgan.services.service.persistence.ProcessOrderDetailPersistence;
import com.huenei.exolgan.services.service.persistence.ProcessOrderPersistence;
import com.huenei.exolgan.services.service.persistence.ReservationPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the Tramite-Detalle local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.huenei.exolgan.services.service.impl.ProcessOrderDetailLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.huenei.exolgan.services.service.ProcessOrderDetailLocalServiceUtil} to access the Tramite-Detalle local service.
 * </p>
 *
 * @author prochas
 * @see com.huenei.exolgan.services.service.impl.ProcessOrderDetailLocalServiceImpl
 * @see com.huenei.exolgan.services.service.ProcessOrderDetailLocalServiceUtil
 * @generated
 */
public abstract class ProcessOrderDetailLocalServiceBaseImpl
	implements ProcessOrderDetailLocalService {
	/**
	 * Adds the Tramite-Detalle to the database. Also notifies the appropriate model listeners.
	 *
	 * @param processOrderDetail the Tramite-Detalle to add
	 * @return the Tramite-Detalle that was added
	 * @throws SystemException if a system exception occurred
	 */
	public ProcessOrderDetail addProcessOrderDetail(
		ProcessOrderDetail processOrderDetail) throws SystemException {
		processOrderDetail.setNew(true);

		return processOrderDetailPersistence.update(processOrderDetail, false);
	}

	/**
	 * Creates a new Tramite-Detalle with the primary key. Does not add the Tramite-Detalle to the database.
	 *
	 * @param processDetailId the primary key for the new Tramite-Detalle
	 * @return the new Tramite-Detalle
	 */
	public ProcessOrderDetail createProcessOrderDetail(long processDetailId) {
		return processOrderDetailPersistence.create(processDetailId);
	}

	/**
	 * Deletes the Tramite-Detalle with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param processDetailId the primary key of the Tramite-Detalle to delete
	 * @throws PortalException if a Tramite-Detalle with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteProcessOrderDetail(long processDetailId)
		throws PortalException, SystemException {
		processOrderDetailPersistence.remove(processDetailId);
	}

	/**
	 * Deletes the Tramite-Detalle from the database. Also notifies the appropriate model listeners.
	 *
	 * @param processOrderDetail the Tramite-Detalle to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteProcessOrderDetail(ProcessOrderDetail processOrderDetail)
		throws SystemException {
		processOrderDetailPersistence.remove(processOrderDetail);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return processOrderDetailPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return processOrderDetailPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return processOrderDetailPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return processOrderDetailPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the Tramite-Detalle with the primary key.
	 *
	 * @param processDetailId the primary key of the Tramite-Detalle to get
	 * @return the Tramite-Detalle
	 * @throws PortalException if a Tramite-Detalle with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ProcessOrderDetail getProcessOrderDetail(long processDetailId)
		throws PortalException, SystemException {
		return processOrderDetailPersistence.findByPrimaryKey(processDetailId);
	}

	/**
	 * Gets a range of all the Tramite-Detalles.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of Tramite-Detalles to return
	 * @param end the upper bound of the range of Tramite-Detalles to return (not inclusive)
	 * @return the range of Tramite-Detalles
	 * @throws SystemException if a system exception occurred
	 */
	public List<ProcessOrderDetail> getProcessOrderDetails(int start, int end)
		throws SystemException {
		return processOrderDetailPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of Tramite-Detalles.
	 *
	 * @return the number of Tramite-Detalles
	 * @throws SystemException if a system exception occurred
	 */
	public int getProcessOrderDetailsCount() throws SystemException {
		return processOrderDetailPersistence.countAll();
	}

	/**
	 * Updates the Tramite-Detalle in the database. Also notifies the appropriate model listeners.
	 *
	 * @param processOrderDetail the Tramite-Detalle to update
	 * @return the Tramite-Detalle that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ProcessOrderDetail updateProcessOrderDetail(
		ProcessOrderDetail processOrderDetail) throws SystemException {
		processOrderDetail.setNew(false);

		return processOrderDetailPersistence.update(processOrderDetail, true);
	}

	/**
	 * Updates the Tramite-Detalle in the database. Also notifies the appropriate model listeners.
	 *
	 * @param processOrderDetail the Tramite-Detalle to update
	 * @param merge whether to merge the Tramite-Detalle with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the Tramite-Detalle that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ProcessOrderDetail updateProcessOrderDetail(
		ProcessOrderDetail processOrderDetail, boolean merge)
		throws SystemException {
		processOrderDetail.setNew(false);

		return processOrderDetailPersistence.update(processOrderDetail, merge);
	}

	/**
	 * Gets the Reserva de salas local service.
	 *
	 * @return the Reserva de salas local service
	 */
	public ReservationLocalService getReservationLocalService() {
		return reservationLocalService;
	}

	/**
	 * Sets the Reserva de salas local service.
	 *
	 * @param reservationLocalService the Reserva de salas local service
	 */
	public void setReservationLocalService(
		ReservationLocalService reservationLocalService) {
		this.reservationLocalService = reservationLocalService;
	}

	/**
	 * Gets the Reserva de salas persistence.
	 *
	 * @return the Reserva de salas persistence
	 */
	public ReservationPersistence getReservationPersistence() {
		return reservationPersistence;
	}

	/**
	 * Sets the Reserva de salas persistence.
	 *
	 * @param reservationPersistence the Reserva de salas persistence
	 */
	public void setReservationPersistence(
		ReservationPersistence reservationPersistence) {
		this.reservationPersistence = reservationPersistence;
	}

	/**
	 * Gets the Tramite local service.
	 *
	 * @return the Tramite local service
	 */
	public ProcessOrderLocalService getProcessOrderLocalService() {
		return processOrderLocalService;
	}

	/**
	 * Sets the Tramite local service.
	 *
	 * @param processOrderLocalService the Tramite local service
	 */
	public void setProcessOrderLocalService(
		ProcessOrderLocalService processOrderLocalService) {
		this.processOrderLocalService = processOrderLocalService;
	}

	/**
	 * Gets the Tramite persistence.
	 *
	 * @return the Tramite persistence
	 */
	public ProcessOrderPersistence getProcessOrderPersistence() {
		return processOrderPersistence;
	}

	/**
	 * Sets the Tramite persistence.
	 *
	 * @param processOrderPersistence the Tramite persistence
	 */
	public void setProcessOrderPersistence(
		ProcessOrderPersistence processOrderPersistence) {
		this.processOrderPersistence = processOrderPersistence;
	}

	/**
	 * Gets the Tramite-Detalle local service.
	 *
	 * @return the Tramite-Detalle local service
	 */
	public ProcessOrderDetailLocalService getProcessOrderDetailLocalService() {
		return processOrderDetailLocalService;
	}

	/**
	 * Sets the Tramite-Detalle local service.
	 *
	 * @param processOrderDetailLocalService the Tramite-Detalle local service
	 */
	public void setProcessOrderDetailLocalService(
		ProcessOrderDetailLocalService processOrderDetailLocalService) {
		this.processOrderDetailLocalService = processOrderDetailLocalService;
	}

	/**
	 * Gets the Tramite-Detalle persistence.
	 *
	 * @return the Tramite-Detalle persistence
	 */
	public ProcessOrderDetailPersistence getProcessOrderDetailPersistence() {
		return processOrderDetailPersistence;
	}

	/**
	 * Sets the Tramite-Detalle persistence.
	 *
	 * @param processOrderDetailPersistence the Tramite-Detalle persistence
	 */
	public void setProcessOrderDetailPersistence(
		ProcessOrderDetailPersistence processOrderDetailPersistence) {
		this.processOrderDetailPersistence = processOrderDetailPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = processOrderDetailPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ReservationLocalService.class)
	protected ReservationLocalService reservationLocalService;
	@BeanReference(type = ReservationPersistence.class)
	protected ReservationPersistence reservationPersistence;
	@BeanReference(type = ProcessOrderLocalService.class)
	protected ProcessOrderLocalService processOrderLocalService;
	@BeanReference(type = ProcessOrderPersistence.class)
	protected ProcessOrderPersistence processOrderPersistence;
	@BeanReference(type = ProcessOrderDetailLocalService.class)
	protected ProcessOrderDetailLocalService processOrderDetailLocalService;
	@BeanReference(type = ProcessOrderDetailPersistence.class)
	protected ProcessOrderDetailPersistence processOrderDetailPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}