/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huenei.exolgan.services.service.base;

import com.huenei.exolgan.services.model.Reservation;
import com.huenei.exolgan.services.service.ReservationLocalService;
import com.huenei.exolgan.services.service.persistence.ReservationPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the Reserva de salas local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.huenei.exolgan.services.service.impl.ReservationLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.huenei.exolgan.services.service.ReservationLocalServiceUtil} to access the Reserva de salas local service.
 * </p>
 *
 * @author prochas
 * @see com.huenei.exolgan.services.service.impl.ReservationLocalServiceImpl
 * @see com.huenei.exolgan.services.service.ReservationLocalServiceUtil
 * @generated
 */
public abstract class ReservationLocalServiceBaseImpl
	implements ReservationLocalService {
	/**
	 * Adds the Reserva de salas to the database. Also notifies the appropriate model listeners.
	 *
	 * @param reservation the Reserva de salas to add
	 * @return the Reserva de salas that was added
	 * @throws SystemException if a system exception occurred
	 */
	public Reservation addReservation(Reservation reservation)
		throws SystemException {
		reservation.setNew(true);

		return reservationPersistence.update(reservation, false);
	}

	/**
	 * Creates a new Reserva de salas with the primary key. Does not add the Reserva de salas to the database.
	 *
	 * @param reservationId the primary key for the new Reserva de salas
	 * @return the new Reserva de salas
	 */
	public Reservation createReservation(long reservationId) {
		return reservationPersistence.create(reservationId);
	}

	/**
	 * Deletes the Reserva de salas with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param reservationId the primary key of the Reserva de salas to delete
	 * @throws PortalException if a Reserva de salas with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteReservation(long reservationId)
		throws PortalException, SystemException {
		reservationPersistence.remove(reservationId);
	}

	/**
	 * Deletes the Reserva de salas from the database. Also notifies the appropriate model listeners.
	 *
	 * @param reservation the Reserva de salas to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteReservation(Reservation reservation)
		throws SystemException {
		reservationPersistence.remove(reservation);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return reservationPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return reservationPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return reservationPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return reservationPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the Reserva de salas with the primary key.
	 *
	 * @param reservationId the primary key of the Reserva de salas to get
	 * @return the Reserva de salas
	 * @throws PortalException if a Reserva de salas with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Reservation getReservation(long reservationId)
		throws PortalException, SystemException {
		return reservationPersistence.findByPrimaryKey(reservationId);
	}

	/**
	 * Gets a range of all the Reserva de salases.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of Reserva de salases to return
	 * @param end the upper bound of the range of Reserva de salases to return (not inclusive)
	 * @return the range of Reserva de salases
	 * @throws SystemException if a system exception occurred
	 */
	public List<Reservation> getReservations(int start, int end)
		throws SystemException {
		return reservationPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of Reserva de salases.
	 *
	 * @return the number of Reserva de salases
	 * @throws SystemException if a system exception occurred
	 */
	public int getReservationsCount() throws SystemException {
		return reservationPersistence.countAll();
	}

	/**
	 * Updates the Reserva de salas in the database. Also notifies the appropriate model listeners.
	 *
	 * @param reservation the Reserva de salas to update
	 * @return the Reserva de salas that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Reservation updateReservation(Reservation reservation)
		throws SystemException {
		reservation.setNew(false);

		return reservationPersistence.update(reservation, true);
	}

	/**
	 * Updates the Reserva de salas in the database. Also notifies the appropriate model listeners.
	 *
	 * @param reservation the Reserva de salas to update
	 * @param merge whether to merge the Reserva de salas with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the Reserva de salas that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Reservation updateReservation(Reservation reservation, boolean merge)
		throws SystemException {
		reservation.setNew(false);

		return reservationPersistence.update(reservation, merge);
	}

	/**
	 * Gets the Reserva de salas local service.
	 *
	 * @return the Reserva de salas local service
	 */
	public ReservationLocalService getReservationLocalService() {
		return reservationLocalService;
	}

	/**
	 * Sets the Reserva de salas local service.
	 *
	 * @param reservationLocalService the Reserva de salas local service
	 */
	public void setReservationLocalService(
		ReservationLocalService reservationLocalService) {
		this.reservationLocalService = reservationLocalService;
	}

	/**
	 * Gets the Reserva de salas persistence.
	 *
	 * @return the Reserva de salas persistence
	 */
	public ReservationPersistence getReservationPersistence() {
		return reservationPersistence;
	}

	/**
	 * Sets the Reserva de salas persistence.
	 *
	 * @param reservationPersistence the Reserva de salas persistence
	 */
	public void setReservationPersistence(
		ReservationPersistence reservationPersistence) {
		this.reservationPersistence = reservationPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = reservationPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ReservationLocalService.class)
	protected ReservationLocalService reservationLocalService;
	@BeanReference(type = ReservationPersistence.class)
	protected ReservationPersistence reservationPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}