/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huenei.exolgan.services.model.impl;

import com.huenei.exolgan.services.model.ProcessOrder;
import com.huenei.exolgan.services.model.ProcessOrderModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the ProcessOrder service. Represents a row in the &quot;EXO_ProcessOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.huenei.exolgan.services.model.ProcessOrderModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProcessOrderImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a Tramite model instance should use the {@link com.huenei.exolgan.services.model.ProcessOrder} interface instead.
 * </p>
 *
 * @author prochas
 * @see ProcessOrderImpl
 * @see com.huenei.exolgan.services.model.ProcessOrder
 * @see com.huenei.exolgan.services.model.ProcessOrderModel
 * @generated
 */
public class ProcessOrderModelImpl extends BaseModelImpl<ProcessOrder>
	implements ProcessOrderModel {
	public static final String TABLE_NAME = "EXO_ProcessOrder";
	public static final Object[][] TABLE_COLUMNS = {
			{ "processOrderId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "userName", new Integer(Types.VARCHAR) },
			{ "createDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "companyName", new Integer(Types.VARCHAR) },
			{ "companyAddress", new Integer(Types.VARCHAR) },
			{ "companyContact", new Integer(Types.VARCHAR) },
			{ "processOrderDescription", new Integer(Types.VARCHAR) },
			{ "processOrderFaliedBy", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table EXO_ProcessOrder (processOrderId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,companyName VARCHAR(75) null,companyAddress VARCHAR(75) null,companyContact VARCHAR(75) null,processOrderDescription VARCHAR(75) null,processOrderFaliedBy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table EXO_ProcessOrder";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.huenei.exolgan.services.model.ProcessOrder"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.huenei.exolgan.services.model.ProcessOrder"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.huenei.exolgan.services.model.ProcessOrder"));

	public ProcessOrderModelImpl() {
	}

	public long getPrimaryKey() {
		return _processOrderId;
	}

	public void setPrimaryKey(long pk) {
		setProcessOrderId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_processOrderId);
	}

	public long getProcessOrderId() {
		return _processOrderId;
	}

	public void setProcessOrderId(long processOrderId) {
		_processOrderId = processOrderId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public String getCompanyName() {
		if (_companyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _companyName;
		}
	}

	public void setCompanyName(String companyName) {
		_companyName = companyName;
	}

	public String getCompanyAddress() {
		if (_companyAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _companyAddress;
		}
	}

	public void setCompanyAddress(String companyAddress) {
		_companyAddress = companyAddress;
	}

	public String getCompanyContact() {
		if (_companyContact == null) {
			return StringPool.BLANK;
		}
		else {
			return _companyContact;
		}
	}

	public void setCompanyContact(String companyContact) {
		_companyContact = companyContact;
	}

	public String getProcessOrderDescription() {
		if (_processOrderDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _processOrderDescription;
		}
	}

	public void setProcessOrderDescription(String processOrderDescription) {
		_processOrderDescription = processOrderDescription;
	}

	public String getProcessOrderFaliedBy() {
		if (_processOrderFaliedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _processOrderFaliedBy;
		}
	}

	public void setProcessOrderFaliedBy(String processOrderFaliedBy) {
		_processOrderFaliedBy = processOrderFaliedBy;
	}

	public ProcessOrder toEscapedModel() {
		if (isEscapedModel()) {
			return (ProcessOrder)this;
		}
		else {
			return (ProcessOrder)Proxy.newProxyInstance(ProcessOrder.class.getClassLoader(),
				new Class[] { ProcessOrder.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					ProcessOrder.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		ProcessOrderImpl processOrderImpl = new ProcessOrderImpl();

		processOrderImpl.setProcessOrderId(getProcessOrderId());

		processOrderImpl.setCompanyId(getCompanyId());

		processOrderImpl.setUserId(getUserId());

		processOrderImpl.setUserName(getUserName());

		processOrderImpl.setCreateDate(getCreateDate());

		processOrderImpl.setModifiedDate(getModifiedDate());

		processOrderImpl.setCompanyName(getCompanyName());

		processOrderImpl.setCompanyAddress(getCompanyAddress());

		processOrderImpl.setCompanyContact(getCompanyContact());

		processOrderImpl.setProcessOrderDescription(getProcessOrderDescription());

		processOrderImpl.setProcessOrderFaliedBy(getProcessOrderFaliedBy());

		return processOrderImpl;
	}

	public int compareTo(ProcessOrder processOrder) {
		long pk = processOrder.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ProcessOrder processOrder = null;

		try {
			processOrder = (ProcessOrder)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = processOrder.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{processOrderId=");
		sb.append(getProcessOrderId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", companyName=");
		sb.append(getCompanyName());
		sb.append(", companyAddress=");
		sb.append(getCompanyAddress());
		sb.append(", companyContact=");
		sb.append(getCompanyContact());
		sb.append(", processOrderDescription=");
		sb.append(getProcessOrderDescription());
		sb.append(", processOrderFaliedBy=");
		sb.append(getProcessOrderFaliedBy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.huenei.exolgan.services.model.ProcessOrder");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>processOrderId</column-name><column-value><![CDATA[");
		sb.append(getProcessOrderId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyName</column-name><column-value><![CDATA[");
		sb.append(getCompanyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyAddress</column-name><column-value><![CDATA[");
		sb.append(getCompanyAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyContact</column-name><column-value><![CDATA[");
		sb.append(getCompanyContact());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>processOrderDescription</column-name><column-value><![CDATA[");
		sb.append(getProcessOrderDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>processOrderFaliedBy</column-name><column-value><![CDATA[");
		sb.append(getProcessOrderFaliedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _processOrderId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _companyName;
	private String _companyAddress;
	private String _companyContact;
	private String _processOrderDescription;
	private String _processOrderFaliedBy;
	private transient ExpandoBridge _expandoBridge;
}