/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huenei.exolgan.services.model.impl;

import com.huenei.exolgan.services.model.Reservation;
import com.huenei.exolgan.services.model.ReservationModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the Reservation service. Represents a row in the &quot;EXO_Reservation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.huenei.exolgan.services.model.ReservationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReservationImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a Reserva de salas model instance should use the {@link com.huenei.exolgan.services.model.Reservation} interface instead.
 * </p>
 *
 * @author prochas
 * @see ReservationImpl
 * @see com.huenei.exolgan.services.model.Reservation
 * @see com.huenei.exolgan.services.model.ReservationModel
 * @generated
 */
public class ReservationModelImpl extends BaseModelImpl<Reservation>
	implements ReservationModel {
	public static final String TABLE_NAME = "EXO_Reservation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "reservationId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "userName", new Integer(Types.VARCHAR) },
			{ "createDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "reservationTimestamp", new Integer(Types.TIMESTAMP) },
			{ "reservationDuration", new Integer(Types.BIGINT) },
			{ "companyName", new Integer(Types.VARCHAR) },
			{ "meetingRoom", new Integer(Types.VARCHAR) },
			{ "visitNames", new Integer(Types.VARCHAR) },
			{ "visitDocs", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table EXO_Reservation (reservationId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,reservationTimestamp DATE null,reservationDuration LONG,companyName VARCHAR(75) null,meetingRoom VARCHAR(75) null,visitNames VARCHAR(75) null,visitDocs VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table EXO_Reservation";
	public static final String ORDER_BY_JPQL = " ORDER BY reservation.reservationTimestamp ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EXO_Reservation.reservationTimestamp ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.huenei.exolgan.services.model.Reservation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.huenei.exolgan.services.model.Reservation"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.huenei.exolgan.services.model.Reservation"));

	public ReservationModelImpl() {
	}

	public long getPrimaryKey() {
		return _reservationId;
	}

	public void setPrimaryKey(long pk) {
		setReservationId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_reservationId);
	}

	public long getReservationId() {
		return _reservationId;
	}

	public void setReservationId(long reservationId) {
		_reservationId = reservationId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public Date getReservationTimestamp() {
		return _reservationTimestamp;
	}

	public void setReservationTimestamp(Date reservationTimestamp) {
		_reservationTimestamp = reservationTimestamp;
	}

	public long getReservationDuration() {
		return _reservationDuration;
	}

	public void setReservationDuration(long reservationDuration) {
		_reservationDuration = reservationDuration;
	}

	public String getCompanyName() {
		if (_companyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _companyName;
		}
	}

	public void setCompanyName(String companyName) {
		_companyName = companyName;
	}

	public String getMeetingRoom() {
		if (_meetingRoom == null) {
			return StringPool.BLANK;
		}
		else {
			return _meetingRoom;
		}
	}

	public void setMeetingRoom(String meetingRoom) {
		_meetingRoom = meetingRoom;
	}

	public String getVisitNames() {
		if (_visitNames == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitNames;
		}
	}

	public void setVisitNames(String visitNames) {
		_visitNames = visitNames;
	}

	public String getVisitDocs() {
		if (_visitDocs == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitDocs;
		}
	}

	public void setVisitDocs(String visitDocs) {
		_visitDocs = visitDocs;
	}

	public Reservation toEscapedModel() {
		if (isEscapedModel()) {
			return (Reservation)this;
		}
		else {
			return (Reservation)Proxy.newProxyInstance(Reservation.class.getClassLoader(),
				new Class[] { Reservation.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					Reservation.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		ReservationImpl reservationImpl = new ReservationImpl();

		reservationImpl.setReservationId(getReservationId());

		reservationImpl.setCompanyId(getCompanyId());

		reservationImpl.setUserId(getUserId());

		reservationImpl.setUserName(getUserName());

		reservationImpl.setCreateDate(getCreateDate());

		reservationImpl.setModifiedDate(getModifiedDate());

		reservationImpl.setReservationTimestamp(getReservationTimestamp());

		reservationImpl.setReservationDuration(getReservationDuration());

		reservationImpl.setCompanyName(getCompanyName());

		reservationImpl.setMeetingRoom(getMeetingRoom());

		reservationImpl.setVisitNames(getVisitNames());

		reservationImpl.setVisitDocs(getVisitDocs());

		return reservationImpl;
	}

	public int compareTo(Reservation reservation) {
		int value = 0;

		value = DateUtil.compareTo(getReservationTimestamp(),
				reservation.getReservationTimestamp());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Reservation reservation = null;

		try {
			reservation = (Reservation)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = reservation.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{reservationId=");
		sb.append(getReservationId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", reservationTimestamp=");
		sb.append(getReservationTimestamp());
		sb.append(", reservationDuration=");
		sb.append(getReservationDuration());
		sb.append(", companyName=");
		sb.append(getCompanyName());
		sb.append(", meetingRoom=");
		sb.append(getMeetingRoom());
		sb.append(", visitNames=");
		sb.append(getVisitNames());
		sb.append(", visitDocs=");
		sb.append(getVisitDocs());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.huenei.exolgan.services.model.Reservation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>reservationId</column-name><column-value><![CDATA[");
		sb.append(getReservationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reservationTimestamp</column-name><column-value><![CDATA[");
		sb.append(getReservationTimestamp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reservationDuration</column-name><column-value><![CDATA[");
		sb.append(getReservationDuration());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyName</column-name><column-value><![CDATA[");
		sb.append(getCompanyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>meetingRoom</column-name><column-value><![CDATA[");
		sb.append(getMeetingRoom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitNames</column-name><column-value><![CDATA[");
		sb.append(getVisitNames());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitDocs</column-name><column-value><![CDATA[");
		sb.append(getVisitDocs());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _reservationId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private Date _reservationTimestamp;
	private long _reservationDuration;
	private String _companyName;
	private String _meetingRoom;
	private String _visitNames;
	private String _visitDocs;
	private transient ExpandoBridge _expandoBridge;
}