/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huenei.exolgan.services.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProcessOrder service. Represents a row in the &quot;EXO_ProcessOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.huenei.exolgan.services.model.impl.ProcessOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.huenei.exolgan.services.model.impl.ProcessOrderImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a Tramite model instance should use the {@link ProcessOrder} interface instead.
 * </p>
 *
 * @author prochas
 * @see ProcessOrder
 * @see com.huenei.exolgan.services.model.impl.ProcessOrderImpl
 * @see com.huenei.exolgan.services.model.impl.ProcessOrderModelImpl
 * @generated
 */
public interface ProcessOrderModel extends BaseModel<ProcessOrder> {
	/**
	 * Gets the primary key of this Tramite.
	 *
	 * @return the primary key of this Tramite
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Tramite
	 *
	 * @param pk the primary key of this Tramite
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the process order id of this Tramite.
	 *
	 * @return the process order id of this Tramite
	 */
	public long getProcessOrderId();

	/**
	 * Sets the process order id of this Tramite.
	 *
	 * @param processOrderId the process order id of this Tramite
	 */
	public void setProcessOrderId(long processOrderId);

	/**
	 * Gets the company id of this Tramite.
	 *
	 * @return the company id of this Tramite
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this Tramite.
	 *
	 * @param companyId the company id of this Tramite
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this Tramite.
	 *
	 * @return the user id of this Tramite
	 */
	public long getUserId();

	/**
	 * Sets the user id of this Tramite.
	 *
	 * @param userId the user id of this Tramite
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this Tramite.
	 *
	 * @return the user uuid of this Tramite
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Tramite.
	 *
	 * @param userUuid the user uuid of this Tramite
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this Tramite.
	 *
	 * @return the user name of this Tramite
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this Tramite.
	 *
	 * @param userName the user name of this Tramite
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this Tramite.
	 *
	 * @return the create date of this Tramite
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this Tramite.
	 *
	 * @param createDate the create date of this Tramite
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this Tramite.
	 *
	 * @return the modified date of this Tramite
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Tramite.
	 *
	 * @param modifiedDate the modified date of this Tramite
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the company name of this Tramite.
	 *
	 * @return the company name of this Tramite
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this Tramite.
	 *
	 * @param companyName the company name of this Tramite
	 */
	public void setCompanyName(String companyName);

	/**
	 * Gets the company address of this Tramite.
	 *
	 * @return the company address of this Tramite
	 */
	@AutoEscape
	public String getCompanyAddress();

	/**
	 * Sets the company address of this Tramite.
	 *
	 * @param companyAddress the company address of this Tramite
	 */
	public void setCompanyAddress(String companyAddress);

	/**
	 * Gets the company contact of this Tramite.
	 *
	 * @return the company contact of this Tramite
	 */
	@AutoEscape
	public String getCompanyContact();

	/**
	 * Sets the company contact of this Tramite.
	 *
	 * @param companyContact the company contact of this Tramite
	 */
	public void setCompanyContact(String companyContact);

	/**
	 * Gets the process order description of this Tramite.
	 *
	 * @return the process order description of this Tramite
	 */
	@AutoEscape
	public String getProcessOrderDescription();

	/**
	 * Sets the process order description of this Tramite.
	 *
	 * @param processOrderDescription the process order description of this Tramite
	 */
	public void setProcessOrderDescription(String processOrderDescription);

	/**
	 * Gets the process order failed by of this Tramite.
	 *
	 * @return the process order failed by of this Tramite
	 */
	@AutoEscape
	public String getProcessOrderFailedBy();

	/**
	 * Sets the process order failed by of this Tramite.
	 *
	 * @param processOrderFailedBy the process order failed by of this Tramite
	 */
	public void setProcessOrderFailedBy(String processOrderFailedBy);

	/**
	 * Gets a copy of this Tramite as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public ProcessOrder toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProcessOrder processOrder);

	public int hashCode();

	public String toString();

	public String toXmlString();
}