/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huenei.exolgan.services.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Reservation service. Represents a row in the &quot;EXO_Reservation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.huenei.exolgan.services.model.impl.ReservationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.huenei.exolgan.services.model.impl.ReservationImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a Reserva de salas model instance should use the {@link Reservation} interface instead.
 * </p>
 *
 * @author prochas
 * @see Reservation
 * @see com.huenei.exolgan.services.model.impl.ReservationImpl
 * @see com.huenei.exolgan.services.model.impl.ReservationModelImpl
 * @generated
 */
public interface ReservationModel extends BaseModel<Reservation> {
	/**
	 * Gets the primary key of this Reserva de salas.
	 *
	 * @return the primary key of this Reserva de salas
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Reserva de salas
	 *
	 * @param pk the primary key of this Reserva de salas
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the reservation id of this Reserva de salas.
	 *
	 * @return the reservation id of this Reserva de salas
	 */
	public long getReservationId();

	/**
	 * Sets the reservation id of this Reserva de salas.
	 *
	 * @param reservationId the reservation id of this Reserva de salas
	 */
	public void setReservationId(long reservationId);

	/**
	 * Gets the company id of this Reserva de salas.
	 *
	 * @return the company id of this Reserva de salas
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this Reserva de salas.
	 *
	 * @param companyId the company id of this Reserva de salas
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this Reserva de salas.
	 *
	 * @return the user id of this Reserva de salas
	 */
	public long getUserId();

	/**
	 * Sets the user id of this Reserva de salas.
	 *
	 * @param userId the user id of this Reserva de salas
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this Reserva de salas.
	 *
	 * @return the user uuid of this Reserva de salas
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Reserva de salas.
	 *
	 * @param userUuid the user uuid of this Reserva de salas
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this Reserva de salas.
	 *
	 * @return the user name of this Reserva de salas
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this Reserva de salas.
	 *
	 * @param userName the user name of this Reserva de salas
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this Reserva de salas.
	 *
	 * @return the create date of this Reserva de salas
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this Reserva de salas.
	 *
	 * @param createDate the create date of this Reserva de salas
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this Reserva de salas.
	 *
	 * @return the modified date of this Reserva de salas
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Reserva de salas.
	 *
	 * @param modifiedDate the modified date of this Reserva de salas
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the reservation timestamp of this Reserva de salas.
	 *
	 * @return the reservation timestamp of this Reserva de salas
	 */
	public Date getReservationTimestamp();

	/**
	 * Sets the reservation timestamp of this Reserva de salas.
	 *
	 * @param reservationTimestamp the reservation timestamp of this Reserva de salas
	 */
	public void setReservationTimestamp(Date reservationTimestamp);

	/**
	 * Gets the reservation duration of this Reserva de salas.
	 *
	 * @return the reservation duration of this Reserva de salas
	 */
	public long getReservationDuration();

	/**
	 * Sets the reservation duration of this Reserva de salas.
	 *
	 * @param reservationDuration the reservation duration of this Reserva de salas
	 */
	public void setReservationDuration(long reservationDuration);

	/**
	 * Gets the company name of this Reserva de salas.
	 *
	 * @return the company name of this Reserva de salas
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this Reserva de salas.
	 *
	 * @param companyName the company name of this Reserva de salas
	 */
	public void setCompanyName(String companyName);

	/**
	 * Gets the meeting room of this Reserva de salas.
	 *
	 * @return the meeting room of this Reserva de salas
	 */
	@AutoEscape
	public String getMeetingRoom();

	/**
	 * Sets the meeting room of this Reserva de salas.
	 *
	 * @param meetingRoom the meeting room of this Reserva de salas
	 */
	public void setMeetingRoom(String meetingRoom);

	/**
	 * Gets the visit names of this Reserva de salas.
	 *
	 * @return the visit names of this Reserva de salas
	 */
	@AutoEscape
	public String getVisitNames();

	/**
	 * Sets the visit names of this Reserva de salas.
	 *
	 * @param visitNames the visit names of this Reserva de salas
	 */
	public void setVisitNames(String visitNames);

	/**
	 * Gets the visit docs of this Reserva de salas.
	 *
	 * @return the visit docs of this Reserva de salas
	 */
	@AutoEscape
	public String getVisitDocs();

	/**
	 * Sets the visit docs of this Reserva de salas.
	 *
	 * @param visitDocs the visit docs of this Reserva de salas
	 */
	public void setVisitDocs(String visitDocs);

	/**
	 * Gets a copy of this Reserva de salas as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Reservation toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Reservation reservation);

	public int hashCode();

	public String toString();

	public String toXmlString();
}